#!/usr/bin/php
<?php
/**
 * Created by Phychion, <wudiweb@gmail.com>
 * Site: http://www.wudiweb.com/
 * Date: 14-02-17
 * Time: 上午9:30
 */

if(sizeof($argv) < 3){
    $help = <<<EOF
Usage: ./myengine --host= --user= --pass= --db= --engine=
\n
--host= mysql host, default is 127.0.0.1
--user= mysql user, default is root
--pass= mysql password
--db= database name
--engine= table engine, default is INNODB, you can set it as MYISAM
\n
EOF;
    echo $help;
    exit;
}

$host = '127.0.0.1';    //mysql host
$user = 'root';     //mysql user
$pass = '';     //mysql password
$db = '';     //database name
$engine = 'INNODB';     //database name

//parse argv
foreach($argv as $arg){
    if(substr($arg,0,2) == '--'){
        if(substr($arg,0,7) == '--host='){
            $host = trim(str_ireplace('--host=','',$arg));
        }elseif(substr($arg,0,7) == '--user='){
            $user = trim(str_ireplace('--user=','',$arg));
        }elseif(substr($arg,0,7) == '--pass='){
            $pass = trim(str_ireplace('--pass=','',$arg));
        }elseif(substr($arg,0,5) == '--db='){
            $db = trim(str_ireplace('--db=','',$arg));
        }elseif(substr($arg,0,9) == '--engine='){
            $engine = trim(str_ireplace('--engine=','',$arg));
        }
    }
}

if(empty($pass) || empty($db)){
    exit("Please specify the mysql password and database name.");
}

$link = mysql_connect($host,$user,$pass);
if(!$link){
    exit("Sorry, cannot connect to mysql server, username or password may be wrong.");
}
if(!mysql_select_db($db,$link)){
    exit("Sorry, cannot use db: $db.");
}

$rst = mysql_query("SHOW TABLES",$link);
$rows_num = 0;
while($row = mysql_fetch_array($rst)){
    $table_name = $row[0];
    $af_rows = mysql_query("ALTER TABLE `$table_name` ENGINE=$engine");
    if($af_rows > 0){
        echo "$table_name: $engine, OK\n";
    }
    $rows_num++;
}
if($rows_num > 0){
    exit("Finish.");
}else{
    exit("There is no any tables need to be altered engine.");
}
